### ISSUE TITLE
Please support esling-plugin-jsdoc 48.0.2

### ISSUE THREAD

**Issue by fhg-isi** [eslint-recommended/eslint-config#202]
Found: eslint-plugin-jsdoc@48.0.2
npm ERR! node_modules/eslint-plugin-jsdoc
npm ERR!   dev eslint-plugin-jsdoc@"48.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint-plugin-jsdoc@"^46.0.0" from @eslint-recommended/eslint-config@16.0.3
npm ERR! node_modules/@eslint-recommended/eslint-config
npm ERR!   dev @eslint-recommended/eslint-config@"16.0.3" from the root project

**Comment by munierujp** [comment]
@fhg-isi The dependent eslint-plugin-jsdoc has been updated to v48 in [v18.0.0](https://github.com/eslint-recommended/eslint-config/releases/tag/v18.0.0).
